export const bookProps = {
  style: {},
  width: 471,
  height: 600,
  minWidth: 0,
  maxWidth: 0,
  minHeight: 0,
  maxHeight: 0,
  drawShadow: false,
  flippingTime: 500,
  usePortrait: false,
  startZIndex: 0,
  autoSize: true,
  maxShadowOpacity: 0,
  mobileScrollSupport: false,
  clickEventForward: true,
  useMouseEvents: true,
  swipeDistance: 0,
  showPageCorners: false,
  disableFlipByClick: false,
};
